# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs


-   repo: https://github.com/qsoyq/precommit
    rev: v0.0.4
    hooks:
      - id: check-poetry-package-version
        args: [--log_level=20]
        always_run: true
        pass_filenames: false
        verbose: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.9
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: "v0.910"
#     hooks:
#     -   id: mypy
#         args: [--config=pyproject.toml]
#         additional_dependencies:
#             - pydantic
#             - sqlalchemy-stubs
